export const frontCrad = [
  {
    id: 1,
    img1:"https://www.tourmyindia.com/imagess/mumbai-tour.webp",
    img2:"https://images.pexels.com/photos/27662410/pexels-photo-27662410.jpeg",
    header:"Camper is the best way to find camping tours. Let’s make the most memorable adventures.",
    Des:"Camper Tour is an incredible way to have an adventurous outdoor experience of world-renowned national parks and wilderness destinations while hiking with only a light daypack and sleeping soundly in comfortable, vehicle-accessible camps.",
    num1:"1980",
    num2:"1000+",
    p1:"The First Trip We Operated",
    p2:"Locations Worldwide",
  },
    {
    id: 2,
    img1:"/src/assets/carousel/i4.jpg",
    img2:"https://images.pexels.com/photos/27662410/pexels-photo-27662410.jpeg",
    header:"Camper is the best way to find camping tours. Let’s make the most memorable adventures.",
    Des:"Camper Tour is an incredible way to have an adventurous outdoor experience of world-renowned national parks and wilderness destinations while hiking with only a light daypack and sleeping soundly in comfortable, vehicle-accessible camps.",
    num1:"1980",
    num2:"2000+",
    p1:"The First Trip We Operated",
    p2:"Locations Worldwide",
  },
  {
    id: 3,
    img1:"https://www.tourmyindia.com/imagess/mumbai-tour.webp",
    img2:"https://images.pexels.com/photos/27662410/pexels-photo-27662410.jpeg",
    header:"Camper is the best way to find camping tours. Let’s make the most memorable adventures.",
    Des:"Camper Tour is an incredible way to have an adventurous outdoor experience of world-renowned national parks and wilderness destinations while hiking with only a light daypack and sleeping soundly in comfortable, vehicle-accessible camps.",
    num1:"1980",
    num2:"3000+",
    p1:"The First Trip We Operated",
    p2:"Locations Worldwide",
  },
  {
    id: 4,
    img1:"https://www.tourmyindia.com/imagess/mumbai-tour.webp",
    img2:"https://images.pexels.com/photos/27662410/pexels-photo-27662410.jpeg",
    header:"Camper is the best way to find camping tours. Let’s make the most memorable adventures.",
    Des:"Camper Tour is an incredible way to have an adventurous outdoor experience of world-renowned national parks and wilderness destinations while hiking with only a light daypack and sleeping soundly in comfortable, vehicle-accessible camps.",
    num1:"1980",
    num2:"4000+",
    p1:"The First Trip We Operated",
    p2:"Locations Worldwide",
  },

]